### ISSUE TITLE
[JavaScript Patterns] Добавить англоязычное наименование паттернов

### ISSUE THREAD

**Issue by zlocate** [ValeriyDyachenko/bxnotes#76]
В среде разработчиков англоязычные наименования более устоявшиеся.
Отказываться от русских вариантов наименования не стоит, однако на мой взгляд полезно (особенно для начинающих) указывать также английское наименование для облегчения поиска расширенной / альтернативной информации
Если комьюнити одобрит решение - оформлю PR с соответствующими правками

**Comment by ValeriyDyachenko** [comment]
@zlocate  Согласен. Я за то, чтобы любой термин в статье, при первом упоминании сопровождался общепринятым англоязычным названием. За исключением заголовков, чтобы не делать пункты меню слишком длинными.

Формат такой:
_переведенный-термин_ (_англоязычный-термин_)

Верстка:
```*переведенный-термин* (<span lang="en">англоязычный-термин</span>)```

> Если комьюнити одобрит решение - оформлю PR с соответствующими правками

Я за, можешь делать. Стиль шрифта для ```<span lang="en"></span>``` должен быть курсивным, но это я могу сам добавить, если что.
