### ISSUE TITLE
[Курс современного JavaScript] Добавить упоминание о поведении Promise.all

### ISSUE THREAD

**Issue by zlocate** [ValeriyDyachenko/bxnotes#78]
Promise.all заreject'иться после первого reject'a любого из переданных промисов, что порой бывает нежелательно. (и неожиданно для новичков)
Заметки не претендуют на полноту документации (есть тот же MDN), но указать это на мой взгляд стоит.

**Comment by zlocate** [comment]
Кроме того, стоит отметить что Promise.all не дает контроля над конкуретностью, например нельзя ограничить число параллельных задач, что может быть критичным при ряде случаев, например если стоит задача параллельного обращения к методам API с rate-limit'ами.
Могу дополнить этот аспект при необходимости

**Comment by ValeriyDyachenko** [comment]
@zlocate В целом я согласен с этим предложением. Но нужно решить, как лучше об этом рассказать.

Я бы предложил добавить еще 2 статьи сразу после текущей про промисы -"Promise API" и "Примеры Promise". В первой будет кратко рассмотрено Promise API (then, catch, finally, resolve, reject, all, allSettled, race). Во второй приведены кейсы их использования. И с учетом этой новой информации отредактировать текущую статью про промисы, чтобы она была, как быстрое введение в промисы.

Получится 3 статьи:
1) текущая (сравнение промисов с "callback hell" для быстрого понимания, какой профит от промисов)
2) Описание API
3) Примеры использования
